version: '2.1'

networks:
  wen-net:
    driver: bridge

services:
  wend:
    build: .
    container_name: wen
    restart: unless-stopped
    networks:
      - wen-net

    environment:
      - TOKEN=${TOKEN}
